[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "design.psiderman.com/*"
to = "/design/:splat"
status = 200

[[redirects]]
from = "now.psiderman.com/*"
to = "/now/:splat"
status = 200
